pre-commit: pre-commit runs mypy *in its own venv*
As such it doesn't have access to any extra modules you installed for your
program, or manually running `mypy <file>`.

So, leverage `additional_dependencies` to list anything that mypy ends
up complaining "that's not installed". Ref:

plugins\eddn.py:40: error: Library stubs not installed for "requests" (or incompatible with Python 3.10)
plugins\eddn.py:40: note: Hint: "python3 -m pip install types-requests"
plugins\eddn.py:40: note: (or run "mypy --install-types" to install all missing stub packages)
plugins\eddn.py:40: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)